
times = [
    {"id": 1, "nome": "Barcelona", "cidade": "Barcelona"},
    {"id": 2, "nome": "Real Madrid", "cidade": "Madrid"},
    {"id": 3, "nome": "Manchester City", "cidade": "Manchester"},
    {"id": 4, "nome": "Bayern de Munique", "cidade": "Munique"},
    {"id": 5, "nome": "Paris Saint-Germain", "cidade": "Paris"},
    {"id": 6, "nome": "Chelsea", "cidade": "Londres"},
    {"id": 7, "nome": "Liverpool", "cidade": "Liverpool"},
    {"id": 8, "nome": "Juventus", "cidade": "Turim"}
]





jogadores = [
    {"id": 1, "nome": "Cristiano", "idade": 36, "posicao": "Atacante", "time_id": 1},
    {"id": 2, "nome": "Lionel", "idade": 34, "posicao": "Meio-campo", "time_id": 2},
    {"id": 3, "nome": "Neymar", "idade": 29, "posicao": "Atacante", "time_id": 3},
    {"id": 4, "nome": "Kevin", "idade": 28, "posicao": "Defensor", "time_id": 4},
    {"id": 5, "nome": "Robert", "idade": 32, "posicao": "Meio-campo", "time_id": 5},
    {"id": 6, "nome": "Mohamed", "idade": 29, "posicao": "Atacante", "time_id": 6},
    {"id": 7, "nome": "Sergio", "idade": 35, "posicao": "Defensor", "time_id": 7},
    {"id": 8, "nome": "Virgil", "idade": 30, "posicao": "Defensor", "time_id": 8},
    {"id": 9, "nome": "Kylian", "idade": 23, "posicao": "Atacante", "time_id": 1},
    {"id": 10, "nome": "Bruno", "idade": 31, "posicao": "Meio-campo", "time_id": 2},
    {"id": 11, "nome": "Antoine", "idade": 30, "posicao": "Atacante", "time_id": 3},
    {"id": 12, "nome": "Luka", "idade": 26, "posicao": "Meio-campo", "time_id": 4},
    {"id": 13, "nome": "Joshua", "idade": 25, "posicao": "Defensor", "time_id": 5},
    {"id": 14, "nome": "Harry", "idade": 27, "posicao": "Atacante", "time_id": 6},
    {"id": 15, "nome": "Jan", "idade": 32, "posicao": "Defensor", "time_id": 7},
    {"id": 16, "nome": "Thomas", "idade": 33, "posicao": "Meio-campo", "time_id": 8},
    {"id": 17, "nome": "Eden", "idade": 29, "posicao": "Atacante", "time_id": 1},
    {"id": 18, "nome": "Thiago", "idade": 28, "posicao": "Meio-campo", "time_id": 2},
    {"id": 19, "nome": "Romelu", "idade": 27, "posicao": "Atacante", "time_id": 3},
    {"id": 20, "nome": "Frenkie", "idade": 24, "posicao": "Meio-campo", "time_id": 4},
    {"id": 21, "nome": "Raphael", "idade": 32, "posicao": "Defensor", "time_id": 5},
    {"id": 22, "nome": "Luis", "idade": 31, "posicao": "Atacante", "time_id": 6},
    {"id": 23, "nome": "Dejan", "idade": 29, "posicao": "Defensor", "time_id": 7},
    {"id": 24, "nome": "Marcelo", "idade": 30, "posicao": "Meio-campo", "time_id": 8},
    {"id": 25, "nome": "Marco", "idade": 28, "posicao": "Defensor", "time_id": 1},
    {"id": 26, "nome": "Karim", "idade": 34, "posicao": "Atacante", "time_id": 2},
    {"id": 27, "nome": "Phil", "idade": 21, "posicao": "Meio-campo", "time_id": 3},
    {"id": 28, "nome": "Ederson", "idade": 28, "posicao": "Goleiro", "time_id": 4},
    {"id": 29, "nome": "Aymeric", "idade": 27, "posicao": "Defensor", "time_id": 5},
    {"id": 30, "nome": "Gabriel", "idade": 24, "posicao": "Atacante", "time_id": 6},
    {"id": 31, "nome": "Rodri", "idade": 25, "posicao": "Meio-campo", "time_id": 7},
    {"id": 32, "nome": "Joao", "idade": 27, "posicao": "Defensor", "time_id": 8},
    {"id": 33, "nome": "Raheem", "idade": 27, "posicao": "Atacante", "time_id":1},
    {"id": 34, "nome": "Manuel", "idade": 35, "posicao": "Goleiro", "time_id": 2},
    {"id": 35, "nome": "Edouard", "idade": 29, "posicao": "Goleiro", "time_id": 3},
    {"id": 36, "nome": "Kingsley", "idade": 25, "posicao": "Atacante", "time_id":4},
    {"id": 37, "nome": "Niklas", "idade": 26, "posicao": "Defensor", "time_id": 5},
    {"id": 38, "nome": "Benjamin", "idade": 25, "posicao": "Defensor", "time_id":6},
    {"id": 39, "nome": "Thomas", "idade": 31, "posicao": "Atacante", "time_id": 7},
    {"id": 40, "nome": "Leroy", "idade": 25, "posicao": "Atacante", "time_id": 8},
    {"id": 41, "nome": "Kylian", "idade": 23, "posicao": "Atacante", "time_id": 1},
    {"id": 42, "nome": "Hakim", "idade": 28, "posicao": "Meio-campo", "time_id": 2},
    {"id": 43, "nome": "Jorginho", "idade": 29, "posicao": "Meio-campo", "time_id": 3},
    {"id": 44, "nome": "Mateo", "idade": 27, "posicao": "Meio-campo", "time_id": 4},
    {"id": 45, "nome": "Reece", "idade": 21, "posicao": "Defensor", "time_id": 5},
    {"id": 46, "nome": "Christian", "idade": 23, "posicao": "Atacante", "time_id": 6},
    {"id": 47, "nome": "Edouard", "idade": 29, "posicao": "Goleiro", "time_id": 7},
    {"id": 48, "nome": "Mason", "idade": 22, "posicao": "Meio-campo", "time_id": 8},
    {"id": 49, "nome": "Tammy", "idade": 24, "posicao": "Atacante", "time_id": 1},
    {"id": 50, "nome": "Ben", "idade": 23, "posicao": "Defensor", "time_id": 2},
    {"id": 51, "nome": "Kurt", "idade": 27, "posicao": "Defensor", "time_id": 3},
    {"id": 52, "nome": "Marc-André", "idade": 29, "posicao": "Goleiro", "time_id": 4},
    {"id": 53, "nome": "Ousmane", "idade": 24, "posicao": "Atacante", "time_id": 5},
    {"id": 54, "nome": "Dayot", "idade": 22, "posicao": "Defensor", "time_id": 6},
    {"id": 55, "nome": "Sergiño", "idade": 21, "posicao": "Defensor", "time_id": 7},
    {"id": 56, "nome": "Neto", "idade": 32, "posicao": "Goleiro", "time_id": 8},
    {"id": 57, "nome": "Sergio", "idade": 35, "posicao": "Meio-campo", "time_id": 1},
    {"id": 58, "nome": "Kai", "idade": 22, "posicao": "Meio-campo", "time_id": 2},
    {"id": 59, "nome": "Timo", "idade": 25, "posicao": "Atacante", "time_id": 3},
    {"id": 60, "nome": "Ben", "idade": 24, "posicao": "Defensor", "time_id": 4},
    {"id": 61, "nome": "Antonio", "idade": 28, "posicao": "Defensor", "time_id": 5},
    {"id": 62, "nome": "Thiago", "idade": 37, "posicao": "Defensor", "time_id": 6},
    {"id": 63, "nome": "Hakim", "idade": 28, "posicao": "Meio-campo", "time_id": 7},
    {"id": 64, "nome": "Jorginho", "idade": 29, "posicao": "Meio-campo", "time_id": 8},
    {"id": 65, "nome": "Mateo", "idade": 27, "posicao": "Meio-campo", "time_id": 1},
    {"id": 66, "nome": "Reece", "idade": 21, "posicao": "Defensor", "time_id": 2},
    {"id": 67, "nome": "Christian", "idade": 23, "posicao": "Atacante", "time_id": 3},
    {"id": 68, "nome": "Edouard", "idade": 29, "posicao": "Goleiro", "time_id": 4},
    {"id": 69, "nome": "Mohamed", "idade": 29, "posicao": "Atacante", "time_id": 5},
    {"id": 70, "nome": "Virgil", "idade": 30, "posicao": "Defensor", "time_id": 6},
    {"id": 71, "nome": "Fabinho", "idade": 27, "posicao": "Meio-campo", "time_id": 7},
    {"id": 72, "nome": "Alisson", "idade": 28, "posicao": "Goleiro", "time_id": 8},
    {"id": 73, "nome": "Sadio", "idade": 29, "posicao": "Atacante", "time_id": 1},
    {"id": 74, "nome": "Trent", "idade": 22, "posicao": "Defensor", "time_id": 2},
    {"id": 75, "nome": "Andrew", "idade": 27, "posicao": "Defensor", "time_id": 3},
    {"id": 76, "nome": "Thiago", "idade": 30, "posicao": "Meio-campo", "time_id": 4},
    {"id": 77, "nome": "Roberto", "idade": 29, "posicao": "Atacante", "time_id": 5},
    {"id": 78, "nome": "Diogo", "idade": 24, "posicao": "Atacante", "time_id": 6},
    {"id": 79, "nome": "Jordan", "idade": 31, "posicao": "Meio-campo", "time_id": 7},
    {"id": 80, "nome": "Cristiano", "idade": 36, "posicao": "Atacante", "time_id": 8},
    {"id": 81, "nome": "Giorgio", "idade": 37, "posicao": "Defensor", "time_id": 1},
    {"id": 82, "nome": "Matthijs", "idade": 21, "posicao": "Defensor", "time_id": 2},
    {"id": 83, "nome": "Wojciech", "idade": 31, "posicao": "Goleiro", "time_id": 3},
    {"id": 84, "nome": "Federico", "idade": 23, "posicao": "Atacante", "time_id": 4},
    {"id": 85, "nome": "Juan", "idade": 33, "posicao": "Defensor", "time_id": 5},
    {"id": 86, "nome": "Weston", "idade": 23, "posicao": "Meio-campo", "time_id":6},
    {"id": 87, "nome": "Aaron", "idade": 30, "posicao": "Meio-campo", "time_id": 7},
    {"id": 88, "nome": "Dejan", "idade": 21, "posicao": "Atacante", "time_id": 8}
]

